### ISSUE TITLE
TypeError Boundingbox Undefined

### ISSUE THREAD

**Issue by patrickahrend** [aws-samples/amazon-textract-response-parser#102]
On some expense bills when I call  `const expense = new TextractExpense(textractResponse);`
I receive this error:  `TypeError: Cannot read properties of undefined (reading 'BoundingBox') ` 

The error is thrown because in the result of Textract an empty Text is detected and there is no Geometry with Boundingbox and Polygon in the JSON object.
The snippet in the JSON, where the error occurs, looks as followed: 
`{
          "Type": { "Text": "CITY", "Confidence": 60.71051788330078 },
          "ValueDetection": { "Text": "", "Confidence": 60.71051788330078 },
          "PageNumber": 1,
          "GroupProperties": [
            {
              "Types": ["RECEIVER"],
              "Id": "a62ec926-a04c-40dd-b59c-f3fbf7249d77"
            }
          ]
        },`

I solved this by adding an if statement to the constructor of `Geometry.js `
![image](https://user-images.githubusercontent.com/57754014/210087362-cdadf2d7-9622-47ec-8a1f-a6cacbcc43d0.png)

**Comment by TheRyanBurke** [comment]
This is impacting my project, too. Thanks for posting a workaround, @patrickahrend !

**Comment by nsantos16** [comment]
Same here!

**Comment by jeff-accountably** [comment]
This affected me as well, I fixed it in my local version by doing this: https://github.com/aws-samples/amazon-textract-response-parser/pull/126

**Comment by Ginga17** [comment]
Thanks a lot for addressing this! I did some preliminary testing, and it works well for me. Tried out using a bunch of .tif files with AnalyseExpense which all previously failed but now work with the NPM patch [0.2.1-alpha.1](https://www.npmjs.com/package/amazon-textract-response-parser/v/0.2.1-alpha.1). I

**Comment by athewsey** [comment]
Thanks @Ginga17 for your help testing the fix! Mainline [v0.2.1](https://www.npmjs.com/package/amazon-textract-response-parser/v/0.2.1) is now published.

Closing this issue as fixed - If anybody finds other cases that are still affected please re-open or create new.
