### ISSUE TITLE
about the source file for textract

### ISSUE THREAD

**Issue by Larbo53** [aws-samples/amazon-textract-response-parser#124]
Good morning,

here is the command I use to extract data from an image. I always use the same name 'test' ='img.png' for the variable 'Name' and response always returns the same result whatever the content of the 'test' file.

How can I get the content of the new 'test' file? Do I have to change the name of the source file every time?

Thanks for your feedback.

Thank you for your feedback.

response = textractmodule.detect_document_text(
    Document={
        'S3Object': {
            'Bucket': s3BucketName,
            'Name': test
            }
            })

**Comment by schadem** [comment]
Is this a question about using Textract or the trp?
