### ISSUE TITLE
Validation Error For Textract Analyze Expense

### ISSUE THREAD

**Issue by victormartingarcia** [aws-samples/amazon-textract-response-parser#135]
Parsing a Textract expense analysis throws a ValidationError:

`{'ExpenseDocuments': {0: {'SummaryFields': {24: {'Currency': ['Unknown field.']}, 25: {'Currency': ['Unknown field.']}, 26: {'Currency': ['Unknown field.']}}, 'Blocks': ['Unknown field.']}, 1: {'Blocks': ['Unknown field.']}}, 'AnalyzeExpenseModelVersion': ['Unknown field.']}`

As done in #40 , we should make the `TAnalyzeExpenseDocumentSchema` ignore unkown fields preventing the marshalling error

**Comment by Godm5** [comment]
Having this same exact error. Please merge https://github.com/aws-samples/amazon-textract-response-parser/pull/136
