### ISSUE TITLE
Instantiating a TextractDocument with a textract result json blob incorrectly prints out a "NextToken" warning

### ISSUE THREAD

**Issue by jorelllinsangan** [aws-samples/amazon-textract-response-parser#154]
We noticed in our project that Textract was logging warnings for a possibly truncated content when instantiating a `TextractDocument` 

> Provided Textract JSON contains a NextToken: Content may be truncated!

I took a closer look at the content we were trying to parse and saw that the key `NextToken` was part of the JSON blob but is just set to null.

```
{
   ...
   "NextToken":null, 
   "StatusMessage":null,
   "Warnings":null
}
```

I found that the constructor of the TextractDocument simply [checks if the key exists](https://github.com/aws-samples/amazon-textract-response-parser/blob/541c07a12d603deed70699357f865d6974369c7b/src-js/src/document.ts#L862-L864) and logs the warning if it does.

```
    if ("NextToken" in this._dict) {
      console.warn(`Provided Textract JSON contains a NextToken: Content may be truncated!`);
    }
```

Probably should be checking for the existence of the key and its value.

**Comment by athewsey** [comment]
Hi & thanks for raising this!

As mentioned in the linked PR, there's an alpha version [0.3.1-alpha.1](https://www.npmjs.com/package/amazon-textract-response-parser/v/0.3.1-alpha.1) now available on NPM with a draft fix. It would be great if you could try it out and let us know whether it resolves your issue?

If possible I'd also like to fix our TRP-side [API type definitions](https://github.com/aws-samples/amazon-textract-response-parser/blob/4155f5ba32c6f76c5eb8bf7892bfc91e21d69a2a/src-js/src/api-models/response.ts#L70) at the same time, as `null` is unexpected here (per e.g. the [GetDocumentAnalysis API doc](https://docs.aws.amazon.com/textract/latest/dg/API_GetDocumentAnalysis.html)). Could you confirm whether:

- The `null`s you're seeing above on `NextToken`, `StatusMessage`, and `Warnings` are coming directly from Amazon Textract API results? Or is there any transformation in your pipeline that could be adding them in?
- Is it the `GetDocumentAnalysis` API where you're observing this? Any other APIs or particular special cases where you're seeing it?

**Comment by jorelllinsangan** [comment]
Hi thanks for looking into this!

1. No. We don't have a data pipeline. The results are straight from Textract. We just specify our own location where the results should be written to. 

2. We actually chose not to use GetDocumentAnalysis. We manually download the analysis result from our s3 bucket.
