### ISSUE TITLE
Errors in ApiTableCellEntityType enumerations

### ISSUE THREAD

**Issue by roysaad** [aws-samples/amazon-textract-response-parser#158]
The type ApiTableCellEntityType is defined as 

export declare const enum ApiTableCellEntityType {
    Title = "TABLE_TITLE",
    Footer = "**FOOTER**",
    SectionTitle = "**SECTION_TITLE**",
    ColumnHeader = "COLUMN_HEADER",
    Summary = "TABLE_SUMMARY"
}
while the entity types returned by Textract are : 
```
KEY | VALUE | COLUMN_HEADER | TABLE_TITLE | TABLE_FOOTER | TABLE_SECTION_TITLE | TABLE_SUMMARY | STRUCTURED_TABLE | SEMI_STRUCTURED_TABLE
```

**FOOTER** should be chaned to **TABLE_FOOTER** and **SECTION_TITLE** should be changed to **TABLE_SECTION_TITLE**

**Comment by athewsey** [comment]
Hi & thanks for raising this. A tentative fix is now published in NPM version [0.3.1-alpha.2](https://www.npmjs.com/package/amazon-textract-response-parser/v/0.3.1-alpha.2): Please try it out and let us know if you find any problems! All being well, will try to roll out the mainline v0.3.1 soon.
