### ISSUE TITLE
Merge_cell call does not work as expected 

### ISSUE THREAD

**Issue by sawasume** [aws-samples/amazon-textract-response-parser#166]
Hello 
I am using this library to parse the json generated by textract.  I have a lot of tables where there are merge cell and I need to get information from such cell and then create csv file from the table 

below is the piece of the code i am using 

with open(table_case_3, 'r') as pfz_doc:
    pfz_textract_json=json.load(pfz_doc)

tdoc = Document(pfz_textract_json)

when I use this call to print the contents of a merge cell I get some text omitted from it 

**table.rows[i].cell[j].mergedText**

Below is an image of cell by cell comparison of a table where the text of interst was **3 or 4 days** but the above call only extracted **3 4**

<img width="715" alt="diff_between_mergedcell_text" src="https://github.com/aws-samples/amazon-textract-response-parser/assets/149112327/4d750a37-f3c6-43d4-a372-518b6df75a11">

Another example where the merged cell text was '**supplied by**'

<img width="543" alt="output" src="https://github.com/aws-samples/amazon-textract-response-parser/assets/149112327/2b70febf-2d13-468d-8759-8c3522257359">

you can see in the image both cell 1 and 2 of row 0 is displaying the same word **supplied** using mergedText call 

where as row 0 cell 2 is displaying the word **by** using .text call 

my expectation is both cell 1 and cell 2 of row 0 should display **supplied by** using mergedText call

**Comment by schadem** [comment]
@sawasume can you share a JSON example?

**Comment by sawasume** [comment]
@schadem  have send it internally via slack
