### ISSUE TITLE
Block type: PARAGRAPH?

### ISSUE THREAD

**Issue by tothniki** [aws-samples/amazon-textract-response-parser#2]
Hi.

Thank you for the sample!

I saw a few intro videos about textract, where they mentioned that there are several block types:  page, paragraph, line, word. But actually there is no paragraph type, is it?

I need to extract paragraphs from a pdf document, so if there is a way to do that too, please let me know!

Thank you!

**Comment by darwaishx** [comment]
Today Textract does not return paragraph as a block type. You can use bounding box information to group lines into paragraphs.
