### ISSUE TITLE
To add fields to ID Document schema

### ISSUE THREAD

**Issue by muktac5** [aws-samples/amazon-textract-response-parser#62]
The ID schema cannot be consistent for all the documents(passport, license, bank cheques etc), so is there any way possible to add new fields to the schema? This way more use cases can be leveraged as it can be used for any document template.

**Comment by schadem** [comment]
Interesting. 
ID schema is specific for ID documents, the generic Textract APIs AnalyzeDocument, DetectDocumentText (and their async Start* and Get*) allow for very flexible definition of documents, which is covered in the trp2.py. 
We may add more domain specific ones over time, so wondering what your use case is.

**Comment by athewsey** [comment]
Closing this stale issue as no further details were provided
