### ISSUE TITLE
Feature Request: Support for queries

### ISSUE THREAD

**Issue by cogwirrel** [aws-samples/amazon-textract-response-parser#64]
There's now a new QUERIES feature type that can be used when analysing a document:

https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-textract-launches-queries-feature-analyze-document-api/

It'd be great if this library could support that :)

**Comment by cogwirrel** [comment]
Ahh I've spotted it in the python trp2 - I'll give that a try :)

**Comment by anjanvb** [comment]
I think [src-js](https://github.com/aws-samples/amazon-textract-response-parser/tree/master/src-js) still needs support for Queries.

**Comment by vsinghipcium** [comment]
+1 for queries in JS

**Comment by kabo** [comment]
yup, I need queries in js as well :slightly_smiling_face:

**Comment by gyadav4** [comment]
+1 really in need
