### ISSUE TITLE
various improvements

### ISSUE THREAD

**Issue by kzaamout** [aws-samples/amazon-textract-response-parser#7]
Hey there,

Thanks for this great project. I found it quite useful. I implemented a few functions in the python version that I would like to submit to you for review. These functions were useful in my case, and I hope they will be useful for others:

1. Field: 

- __repre__

-  __eq__

2. Form: getFieldByKey2: each field key and the search key will be lower() and trim() before comparison. 

3. Table:
- toDictionary: useful for various things, including importing tables into pandas. 
- to2DList: useful for various things, including pandas.

4. Page: added _page_number field and property

If these changes sound interesting, please let me know how to proceed.

**Comment by schadem** [comment]
Hi @kzaamout,
Sorry for the late response. Sounds interesting. I have some items in the works that could be similar to what you are doing.
Conversion functions for tables or forms output could make sense in this project.

Can you create a pull request and let me take a look?

**Comment by schadem** [comment]
no response for a while, closing out.
