### ISSUE TITLE
Python package is not compatible with 3.6

### ISSUE THREAD

**Issue by jeffgabhart** [aws-samples/amazon-textract-response-parser#82]
The import of annotations from `__future__` makes this python package incompatible with python 3.6

https://github.com/aws-samples/amazon-textract-response-parser/blob/7b2727fb0387281871a05944ccd64c04407f286a/src-python/trp/trp2.py#L1

https://github.com/aws-samples/amazon-textract-response-parser/blob/7b2727fb0387281871a05944ccd64c04407f286a/src-python/setup.py#L53

**Comment by schadem** [comment]
We'll update the setup.py. Python 3.6 is past EOL and will no longer be supported.

**Comment by athewsey** [comment]
Verified that setup.py [explicitly sets](https://github.com/aws-samples/amazon-textract-response-parser/blob/e4824cbd69ccd2fc42e967b4273f6dc5b145b784/src-python/setup.py#L51) `python_requires='>=3.8'`. Closing this issue as Python 3.6 is EOL and won't be supported going forward.
