### ISSUE TITLE
[DOCUMENTATION] Wrong package for pip install 

### ISSUE THREAD

**Issue by dgallitelli** [aws-samples/amazon-textract-response-parser#9]
The documentation says, in the `src-python/README.md` file, to install textract-response-parser via `pip install textract-response-parser` but the install does not work - says it's not available in pip. Moreover, the source file is not available anymore.

**Comment by schadem** [comment]
Sorry, fixed the documentation. The correct command is
```
python -m pip install amazon-textract-response-parser
```

The source moved into the __init__.py file to make it easy to migrate from pre-existing code.

Let me know when you still have issues. Will close this for now.
